---
title: "MD7 Demo"
format: html
editor: visual
embed-resources: true
---

```{r}
#| message: false

library(moderndive)
library(tidyverse)
theme_set(theme_light())
```

only 2 points of data

```{r}
swift <- tribble(
  ~catches, ~yards, ~taylor,
       8.5,    108, "Present",
       7.0,   46.5, "Absent"
)

ggplot(swift,
       aes(x = taylor,
           fill = taylor,
           y = yards)) +
  geom_col() +
  labs(x = "Taylor Swift is...",
       y = "Receiving Yards",
       title = "Does Taylor Swift improve Travis Kelce's performances?") +
  theme(legend.position = "none")
```

```{r}
swift2 <- tribble(
  ~gw, ~yds, ~present,
  2, 26,   "Absent",
  3, 69,   "Present",
  4, 60,   "Present",
  5, 67,   "Absent",
  6, 124,  "Present",
  7, 179,  "Present",
  8, 58,   "Absent"
)
```

```{r}
ggplot(swift2,
       aes(x = yds,
           y = "",
           group = present,
           color = present)) +
  geom_jitter(width = .02,
              height = .02) +
  labs(color = "Swift is...",
       y = "",
       x = "Kelce receiving yards")
```

The 95% confidence interval is a measure of uncertainty. Let's talk about it.

Visualize the result.

```{r}
mod1 <- lm(yds ~ present,
           data = swift2)

mod1_coefs <- get_regression_table(mod1)
mod1_coefs
```

```{r}
mod1_coefs |>
  filter(term == "present: Present") |> 
  ggplot(aes(x = estimate,
             xmax = upper_ci,
             xmin = lower_ci,
             y = "")) +
  geom_pointrange() +
  geom_vline(xintercept = 0,
             linetype = "dotted",
             color = "red") +
  scale_x_continuous(breaks = seq(-50, 200, 50),
                     limits = c(-50, 200)) +
  labs(y = "",
       x = "The Swift Effect",
       title = "Effect of Swift's Presence on Kelce's Receiving Yards",
       subtitle = "95% Confidence interval",
       caption = "Data from first 8 game weeks of 2023 NFL Season")
```

0 = neutrality

```{r}
head(bowl, n = 10)
```

```{r}
shovel1 <- bowl |> 
  rep_sample_n(size = 50)

shovel1 %>% 
  mutate(if_red = if_else(color == "red", 1L, 0L)) %>% 
  summarise(prop_red = mean(if_red))
```

```{r}
shovels100 <- 
  bowl %>% 
  rep_sample_n(size = 50,
               reps = 100) %>% 
   mutate(if_red = if_else(color == "red", 1L, 0L)) %>% 
  group_by(replicate) %>% 
  summarise(prop_red = mean(if_red))

shovels100 %>% 
  ggplot(aes(x = prop_red)) +
  geom_histogram(boundary = .5,
                 binwidth = .025,
                 color = "white")
```

```{r}
library(worldfootballR)
```

```{r}
#| cache: true

d <- fb_match_results("ENG",
                       "M", 
                       2023)
```

```{r}
glimpse(d)

lfc2023 <- d |> 
  filter(Home == "Liverpool" | Away == "Liverpool") |> 
  mutate(home_points = case_when(HomeGoals > AwayGoals ~ 3,
                                 HomeGoals < AwayGoals ~ 0,
                                 .default = 1),
         away_points = case_when(HomeGoals < AwayGoals ~ 3,
                                 HomeGoals > AwayGoals ~ 0,
                                 .default = 1),
         lfc_points = if_else(Home == "Liverpool", home_points, away_points),
         matchweek = as.integer(Wk)) |> 
  select(matchweek, lfc_points) |> 
  arrange(matchweek)

glimpse(lfc2023)
```

```{r}
lfc2023 <- lfc2023 |> 
  mutate(ppg_to_date = cumsum(lfc_points) / matchweek)
```

```{r}
ggplot(lfc2023,
       aes(x = matchweek,
           y = ppg_to_date)) +
    geom_hline(yintercept = 67/38, 
               linetype = "dotted") +
    geom_line(color = "red")
```

```{r}
load(here::here("Data", "gss2018.Rdata"))
glimpse(gss2018)

gss2018 <- gss2018 |> 
  mutate(conservative = if_else(polviews >=5, 1L, 0L))
```

```{r}
set.seed(1)

mean(gss2018$conservative) # full sample proportion

gss30 <- gss2018 |> 
  slice_sample(n = 30) |> 
  mutate(sampsize = 30)

gss120 <- gss2018 |> 
  slice_sample(n = 120) |> 
  mutate(sampsize = 120)

gss480 <- gss2018 |> 
  slice_sample(n = 480) |> 
  mutate(sampsize = 480)

gss960 <- gss2018 |> 
  slice_sample(n = 960) |> 
  mutate(sampsize = 960)

gss_all <- gss2018 |> 
  mutate(sampsize = nrow(gss2018))

samples <- bind_rows(gss30, gss120, gss480, gss960, gss_all)

samples |> 
  group_by(sampsize) |> 
  summarize(est_prop = mean(conservative))
```

```{r}
library(tidyverse)
```

ˆ
